config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  get '/pageviews', to: 'home#pageviews', as: 'pageviews'

  mount ShopifyApp::Engine, at: '/'

  namespace :app_proxy do
    root action: 'index'
    # simple routes without a specified controller will go to AppProxyController
    
    # more complex routes will go to controllers in the AppProxy namespace
    # 	resources :reviews
    # GET /app_proxy/reviews will now be routed to
    # AppProxy::ReviewsController#index, for example
  end

  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  include ShopifyApp::Shop
  include ShopifyApp::SessionStorage
end

app/controllers/app_proxy_controller.rb
class AppProxyController < ApplicationController
   include ShopifyApp::AppProxyVerification

  def index
    render layout: false, content_type: 'application/liquid'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ShopifyApp::AuthenticatedController

  def index
    @products = ShopifyAPI::Product.find(:all, params: { limit: 10 })
    @customers = ShopifyAPI::Customer.find(:all)

    all_orders

   end

   def all_orders	
   		@orders = [1]
   		@customers.each do |customer| 
     	@orders.push(customer.orders_count)
     	sum_orders
  		end
   end

   def sum_orders
   	@sum_orders = @orders.reduce(:+)
   end
end

app/controllers/shopify_app/authenticated_controller.rb
module ShopifyApp
  class AuthenticatedController < ApplicationController
    include ShopifyApp::LoginProtection
    before_action :login_again_if_different_shop
    around_action :shopify_session
    layout ShopifyApp.configuration.embedded_app? ? 'embedded_app' : 'application'
  end
end

app/controllers/shopify_app/sessions_controller.rb
module ShopifyApp
  class SessionsController < ApplicationController
    include ShopifyApp::SessionsConcern
  end
end

app/controllers/shopify_app/webhooks_controller.rb
module ShopifyApp
  class WebhooksController < ApplicationController
    include ShopifyApp::WebhookVerification

    class ShopifyApp::MissingWebhookJobError < StandardError; end

    def receive
      params.try(:permit!)
      job_args = {shop_domain: shop_domain, webhook: webhook_params.to_h}
      webhook_job_klass.perform_later(job_args)
      head :no_content
    end

    private

    def webhook_params
      params.except(:controller, :action, :type)
    end

    def webhook_job_klass
      "#{webhook_type.classify}Job".safe_constantize or raise ShopifyApp::MissingWebhookJobError
    end

    def webhook_type
      params[:type]
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/app_proxy/index.html.erb
<h2>App Proxy Page</h2>

<p>Congratulations! You have successfully configured App Proxy for your shopify application.</p>
<p>Any valid liquid code included in this page will be parsed and rendered by Shopify.</p>

<br>

<pre>
Your Shop Details:
<hr>
	Shop Name 			: {{ shop.name }}
	myshopify name 			: {{ shop.permanent_domain }}
	Primary Domain of Shop 		: {{ shop.domain }}
	Shop URL 			: {{ shop.url }}
	Shop Currency 			: {{ shop.currency }}
	No. of products in this shop 	: {{ shop.products_count }}
<br>	
<hr>	
</pre>

app/views/home/index.html.erb
<script type="text/javascript">
  $(document).on('ready', function() {
    var shopifyQL = 'SHOW sum(pageview_count) FROM visits SINCE -1m UNTIL today';
      renderData = function(response) {
        var all_orders = '<%= @sum_orders %>';
        var conversion_rate = all_orders / response.result.data[0] * 100
        $(".result").append(conversion_rate.toFixed(2) + "% conversion_rate");

      };
      ShopifyApp.Analytics.fetch({
        query: shopifyQL,
        success: renderData,
        error: renderData
      });
  });
</script>

<%= link_to "Pageviews Example", pageviews_path %>

<div class='rate'>
<div class="result"></div>
</div>

app/views/home/pageviews.html.erb
<div id="chart"></div>

<script type="text/javascript">
logError = function(error) {
  console.log(error);
};

var exampleData = [
  ["2016-02-28T00:00:00-05:00", 14309, 4397],
  ["2016-02-29T00:00:00-05:00", 13676, 3234],
  ["2016-03-01T00:00:00-05:00", 14782, 4679],
  ["2016-03-02T00:00:00-05:00", 15977, 5272],
  ["2016-03-03T00:00:00-05:00", 14500, 4294],
  ["2016-03-04T00:00:00-05:00", 13963, 4316],
  ["2016-03-05T00:00:00-05:00", 14392, 4304],
  ["2016-03-06T00:00:00-05:00", 15276, 5220],
  ["2016-03-07T00:00:00-05:00", 16330, 5310],
  ["2016-03-08T00:00:00-05:00", 17530, 5863],
  ["2016-03-09T00:00:00-05:00", 18276, 5982],
  ["2016-03-10T00:00:00-05:00", 18638, 6224],
  ["2016-03-11T00:00:00-05:00", 17351, 5418],
  ["2016-03-12T00:00:00-05:00", 19897, 6632],
  ["2016-03-13T00:00:00-05:00", 19141, 6656],
];
</script>

<script type="text/javascript">
var shopifyQL = 'SHOW \
  sum(IF location_country == "United States" THEN pageview_count) AS us_traffic, \
  sum(IF location_country == "Canada" THEN pageview_count) AS ca_traffic \
  OVER day(timestamp) AS day \
  FROM visits \
  SINCE -2w UNTIL today \
  ORDER BY day';

drawGraph = function(response) {
  c3.generate({
    data: {
      x: 'day', columns: Transformer.toC3Format(response.result)
    },
    axis: {
      x: { type: 'timeseries', tick: { format: "%Y-%m-%d" } }
    }
  });
};

ShopifyApp.Analytics.fetch({
  query: shopifyQL,
  success: drawGraph,
  error: logError
});
</script>

app/views/layouts/_flash_messages.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
  var eventName = typeof(Turbolinks) !== 'undefined' ? 'page:change' : 'DOMContentLoaded';

  document.addEventListener(eventName, function() {
    <% if flash[:notice] %>
      ShopifyApp.flashNotice("<%= j flash[:notice].html_safe %>");
    <% end %>

    <% if flash[:error] %>
      ShopifyApp.flashError("<%= j flash[:error].html_safe %>");
    <% end %>
  });
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyShopifyApp</title>
    <%= csrf_meta_tags %>

   
  </head>


  <body>


 
    <%= yield %>
  </body>
</html>

app/views/layouts/embedded_app.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shopify Embedded Example App</title>

  <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/4.3.0/lodash.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.5.15/d3.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.css"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/c3/0.4.10/c3.js"></script>
  <script src="//cdn.shopify.com/s/assets/external/app.js?<%= Time.now.strftime('%Y%m%d%H') %>"></script>
  <script type="text/javascript">
    ShopifyApp.init({
      apiKey: "e991806483601ea2f144ffa7bc871883",
      shopOrigin: '<%= "https://#{ @shop_session.url }" if @shop_session %>'
    });
  </script>

  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <%= yield %>
</body>
</html>